# Header
navname: Honey.Choco.Ink

# navigatior items
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about
  RSS: /rss2.xml

# favicon
favicon: /image/icon.png

# Profile
nickname: Honey.Choco.Ink

### this variable is MarkDown form.
description: 自分が分かればそれでいいというスタンスのメモ置き場。
avatar: /image/honey-logo.jpg

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
# links:
#   Posts: 
#     url: /archives
#     icon: fa-solid fa-book-bookmark
#   RSS:
#     url: /rss2.xml
#     icon: fa-solid fa-square-rss
#   # Category:
#   # Tags: 
#   # Link:
#   # Resume:
#   # Publish:
#   # Trophy:
#   Iceshrimp:
#     url: https://milk.choco.ink/@tachibana
#     icon: fa-solid fa-rocket
#   #Fediverse(Misskey):
#   #  url: https://misskey.noellabo.jp/@tachibana
#   #  icon: fa-rocket 
#   # Pixelfed:
#   #   url: https://vanilla.choco.ink/tachibana
#   #   icon: fa-solid fa-camera-retro
#   Bluesky: 
#     url: https://bsky.app/profile/sweet.choco.ink
#     icon: fa-brands fa-bluesky     
#   # Mastodon: 
#   #   url: https://fedibird.com/@tachibana502
#   #   icon: fa-brands fa-mastodon    
#   Photo Gallery: 
#     url: https://caramel.choco.ink
#     icon: fa-solid fa-photo-film
#   MogMog.Party: 
#     url: https://mogmog.party
#     icon: fa-solid fa-utensils
#   Link: 
#     url: https://citrus.choco.ink
#     icon: fa-solid fa-address-card
  # AliPay:
  #ZhiHu: https://www.zhihu.com/people/sirice
  # LinkedIn:
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  #Instagram:
  #Reddit:
  # YouTube:
  # QQ:
  # Weibo:
  # WeChat:
  #Github: https://github.com/Siricee

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# 最新の投稿
recent_post_items: 5
recent_post_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: false

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: true
post_copyright_slogan_text: Do you believe in <strong>DESTINY</strong>?
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY/MM/DD
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter

socialLinks:
  - href: "https://milk.choco.ink/@tachibana"
    title: "Iceshrimp"
    svgPath: "/icons/fediverse-logo.svg"  # アイコンのパス
  - href: "https://misskey.noellabo.jp/@tachibana"
    title: "Misskey"
    svgPath: "/icons/misskey.svg"  # アイコンのパス
  # - href: "https://fedibird.com/@tachibana502"
  #   title: "Fedibird"
  #   svgPath: "/icons/mastodon.svg"  # アイコンのパス    
  - href: "https://bsky.app/profile/sweet.choco.ink"
    title: "Bluesky"
    svgPath: "/icons/bluesky.svg"  # アイコンのパス
  - href: "https://caramel.choco.ink"
    title: "Caramel.Choco.Ink"
    svgPath: "/icons/camera.svg"  # アイコンのパス                 
  - href: "https://mogmog.party"
    title: "MogMog.Party"
    svgPath: "/icons/mogmog.svg"  # アイコンのパス               
  - href: "https://citrus.choco.ink"
    title: "Citrus.Choco.Ink"
    svgPath: "/icons/orange.svg"  # アイコンのパス    